esphome:
  name: data-logger
  friendly_name: data logger


esp32:
  board: esp32dev
  framework:
    type: esp-idf

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

# ------------------------
# Componente SD_MMC
# ------------------------


# ------------------------
# Sensor INA226
# ------------------------
sensor:
  - platform: ina226
    address: 0x40
    shunt_resistance: 0.01 ohm
    current:
      name: "Corriente"
      id: corriente
    power:
      name: "Potencia"
      id: potencia
    bus_voltage:
      name: "Voltaje"
      id: voltaje
      filters:
        - multiply: 0.9514
    shunt_voltage:
      name: "Voltaje Shunt"
    update_interval: 2s

  - platform: integration
    name: "Energía consumida"
    sensor: potencia
    time_unit: h
    id: energia_consumida

# ------------------------
# Pantalla OLED SSD1306
# ------------------------
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(font1), "V: %.2f V", id(voltaje).state);
      it.printf(0, 16, id(font1), "I: %.2f A", id(corriente).state);
      

font:
  - file: "fonts/arial_narrow_7.ttf"
    id: font1
    size: 14

# ------------------------
# Reloj NTP
# ------------------------


# ------------------------
# Botón de registro
# ------------------------


# ------------------------
# Logger
# ------------------------
logger:
  level: DEBUG